name: Build Packages

on:
  workflow_dispatch:

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: New Version
        id: version
        run: |
          echo "version=$(grep 'PKG_VERSION:=' ./luci-app-radius-monitor/Makefile |awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "New Version: $(grep 'PKG_VERSION:=' ./luci-app-radius-monitor/Makefile |awk -F '=' '{print $2}')"
  
  build:
    needs: Get-Version
    name: Build IPK Radius Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-23.05.0
          FEEDNAME: radiusmonitor
          PACKAGES: luci-app-radius-monitor
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: IPK_RADMON
          path: bin/packages/x86_64/radiusmonitor/*.ipk

      - name: Generate new tag & release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          files: bin/packages/x86_64/radiusmonitor/*.ipk
          tag_name: "v${{ needs.Get-Version.outputs.version }}-beta"