name: Clean jsDelivr Cache

on: 
  push:
    branches: 
      - main
      - radius
    paths-ignore:
      - 'README.md'

jobs:
  jsDelivr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: changed_files
      name: git-changesets
      uses: collin-miller/git-changesets@v0.0.4
      with:
          format: space-delimited

    - name: Clean jsDelivr Cache
      run: |
          for i in ${{ steps.changed_files.outputs.added_modified }}; do
             # echo ${{ steps.changed_files.outputs.all }}
             curl -sL --retry 3 https://purge.jsdelivr.net/gh/rtaserver/RakitanManager@${{ github.ref_name }}/$i
          done
