name: Notify Telegram on Update

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        run: |
          git fetch --prune --unshallow
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHANGED_FILES: ${{ env.CHANGED_FILES }}
        run: |
          MESSAGE="Repository has been updated. Changed files:\n$CHANGED_FILES"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
          -d chat_id=$CHAT_ID \
          -d text="$MESSAGE"
