name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *" 

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Hapus semua file di repository fork
      run: |
        git rm -rf --force .
        git clean -fdx

    - name: Clone source repository
      run: |
        git clone https://github.com/Maizil41/RadiusMonitor.git source_repo
        rsync -a --exclude='.git' source_repo/ .
        rm -rf source_repo

    - name: Push changes to fork
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Release: Auto sync" || echo "No changes to commit"
        git push origin main --force
